#ifndef __DEVICES_H_
#define __DEVICES_H_

#define LIGHT2_GPIO_PORT 	GPIO_P2
#define LIGHT2_GPIO_PIN		GPIO_Pin_6
#define LIGHT1_GPIO_PORT 	GPIO_P2
#define LIGHT1_GPIO_PIN		GPIO_Pin_5

#define SWITCH1_GPIO_PORT 		GPIO_P2
#define SWITCH1_GPIO_PIN		GPIO_Pin_0
#define SWITCH2_GPIO_PORT 		GPIO_P2
#define SWITCH2_GPIO_PIN		GPIO_Pin_1
#define SWITCH3_GPIO_PORT 		GPIO_P2
#define SWITCH3_GPIO_PIN		GPIO_Pin_2
#define SWITCH4_GPIO_PORT 		GPIO_P2
#define SWITCH4_GPIO_PIN		GPIO_Pin_3

#define SWITCH1_ON()	GPIO_SetBit(SWITCH1_GPIO_PORT,SWITCH1_GPIO_PIN)
#define SWITCH1_OFF()	GPIO_ClearBit(SWITCH1_GPIO_PORT,SWITCH1_GPIO_PIN)
#define SWITCH2_ON()	GPIO_SetBit(SWITCH2_GPIO_PORT,SWITCH2_GPIO_PIN)
#define SWITCH2_OFF()	GPIO_ClearBit(SWITCH2_GPIO_PORT,SWITCH2_GPIO_PIN)
#define SWITCH3_ON()	GPIO_SetBit(SWITCH3_GPIO_PORT,SWITCH3_GPIO_PIN)
#define SWITCH3_OFF()	GPIO_ClearBit(SWITCH3_GPIO_PORT,SWITCH3_GPIO_PIN)
#define SWITCH4_ON()	GPIO_SetBit(SWITCH4_GPIO_PORT,SWITCH4_GPIO_PIN)
#define SWITCH4_OFF()	GPIO_ClearBit(SWITCH4_GPIO_PORT,SWITCH4_GPIO_PIN)

#define DH_GPIO_PORT 	GPIO_P4
#define DH_GPIO_PIN		GPIO_Pin_4


#define DH_Pin	P44   //定义数据线

void DevicesControl(u8 *cmd);
void DevicesInit(void);

#endif
