#ifndef __DEVICES_H_
#define __DEVICES_H_

#define LIGHT2_GPIO_PORT 	GPIO_P1
#define LIGHT2_GPIO_PIN		GPIO_Pin_7
#define LIGHT1_GPIO_PORT 	GPIO_P3
#define LIGHT1_GPIO_PIN		GPIO_Pin_7

#define SWITCH1_GPIO_PORT 		GPIO_P5
#define SWITCH1_GPIO_PIN		GPIO_Pin_2
#define SWITCH2_GPIO_PORT 		GPIO_P0
#define SWITCH2_GPIO_PIN		GPIO_Pin_4
#define SWITCH3_GPIO_PORT 		GPIO_P0
#define SWITCH3_GPIO_PIN		GPIO_Pin_1
#define SWITCH4_GPIO_PORT 		GPIO_P0
#define SWITCH4_GPIO_PIN		GPIO_Pin_0

#define SWITCH1_ON()	GPIO_SetBit(SWITCH1_GPIO_PORT,SWITCH1_GPIO_PIN)
#define SWITCH1_OFF()	GPIO_ClearBit(SWITCH1_GPIO_PORT,SWITCH1_GPIO_PIN)
#define SWITCH2_ON()	GPIO_SetBit(SWITCH2_GPIO_PORT,SWITCH2_GPIO_PIN)
#define SWITCH2_OFF()	GPIO_ClearBit(SWITCH2_GPIO_PORT,SWITCH2_GPIO_PIN)
#define SWITCH3_ON()	GPIO_SetBit(SWITCH3_GPIO_PORT,SWITCH3_GPIO_PIN)
#define SWITCH3_OFF()	GPIO_ClearBit(SWITCH3_GPIO_PORT,SWITCH3_GPIO_PIN)
#define SWITCH4_ON()	GPIO_SetBit(SWITCH4_GPIO_PORT,SWITCH4_GPIO_PIN)
#define SWITCH4_OFF()	GPIO_ClearBit(SWITCH4_GPIO_PORT,SWITCH4_GPIO_PIN)

#define DH_GPIO_PORT 	GPIO_P5
#define DH_GPIO_PIN		GPIO_Pin_0


#define DH_Pin	P50   //定义数据线

u8 DevicesControl(u8 *cmd);
void DevicesInit(void);

#endif
